{% set version = "0.0.10" %}

package:
  name: splauncher
  version: {{ version }}

source:
  fn: splauncher-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/s/splauncher/splauncher-{{ version }}.tar.gz
  sha256: 8019ab1dda0470d4f74422ce713fe3cc44d76618f5706aaa1bd9b553d72b3dea

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - splauncher

about:
  home: https://github.com/jakirkham/splauncher
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: A simple subprocess launcher with optional DRMAA support.
  doc_url: https://splauncher.readthedocs.io/
  dev_url: https://github.com/jakirkham/splauncher

extra:
  recipe-maintainers:
    - jakirkham
