travis:
  secure:
    BINSTAR_TOKEN: xdlfJZ+MvMQizojlz//ZeawebiB3ng1HnTPna6l3OT7H4XH/69pQNpBdUW3VSw4Fkv4vh1vDvQjedfenLxYbt5Dhs2gVmV+oESXlNkMAoyoO8YIEBYYhLV/k25fC/qvHsyAcXtj/MhbAii0sp0TFvFmmFBTuuO/vequenqSib37449v8ssU8YBlzJHyYUdHXOnp5pMcyMb/9Y3uFwrXnQf6h1mKxkUafxUdHqDaouvT7UOGPpx80Z+L+7ou/e5vIbkptG+RlKYHS/sLHvbRwnx476Cn3Izikwz36Fdt+MOLmj+G9GOBy0O5nyAjb1C8ISo9N/VuA2sUoxC2iQqS/cif6ZmkhlDO5ZUjj9B2gPYlI2scfxBDpol61UAL2aerXQp17el8vLhA10C0DwcjFjyYNgPenWk3XEvL+FJD7OlvSgL2w7A8ZmoAJ5fyAjOWKMFKna6//Sir9HE7v6M7qCZcdwJ+7LggldVAtSWXFRK39jTGSeiOf1xstPKIxCi0YxaK65uhoByG7V6V2egQ5snDyibQsszI6cjJmD8eXxSNklETsVeYRyCzaEvfLPFpqLtkwmI6XqrWjyTyr4a5p+XsyoXONyCTDz3fEb0vwDlngruuZZZhsrl6wNra46oUxRPH1zsJWvg6mHqBSaPbD1KZQb7GGUpkxf9HCz7HFvjs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
