travis:
  secure:
    BINSTAR_TOKEN: oPJLlo15tdnidx4MIaRDl6bjiumAZjuD41iN1usoj7h7k4Mq5IzlezqRUEIwoItwcOV7QECaFuyz/gfR3+bdyemK6RQYa2WI51H05rPZotZxQJrXQDDtbi/Msr2z1MTrQROeCw9W4PrMc4KHTTAQtzY03ufE0cETAP5UENS+nOfWMGohNYsDSrxhdfIfqvrmoPBaubw5T9rCiep+gziF4+/zHY+kNoHlooxHi6txNZozPAszLA1EE2YSXMywKPCy/Djs3ouoUDUH2Kcsudp49Efh8/Ie+B2VX1W4VzlPK+ryQI83czz/Ts8tasE+oxDDgPSWGiFt/eYdMN5sD2nUaSiA47zKLkiby0vNCurqBiuAQ5D36qx3gd5Hibr4nmjSDTufcAks1kHvhSaL5j49Wn20Er9x2xQ11Mojh/+S81pe4U8y87ZF23L2WNnYvgxJ6EpHnjRaiIob/7+qFhGazc39UDqnzKy6ZeW+I/M3GgCnip72CV3ekum8rfr3KoravqO1CkgNnxBtpKWtWLBGjh8MxKtvDEDR/uhGSFNI36aHAsxJdxYPZgbEnT4c/zQg+mrhHT/HniC01xJw2g0wcdVwjU049Iljfxw2d8Gj5cMHZCTbDiTcbGLSZ4l779ipSPIE83RqkzewlBx+IcKu6hRFPt6M4akZqea6/R/rjkA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
