travis:
  secure:
    BINSTAR_TOKEN: RYxVwttT7t1LJXi4GOgqDc1O+/hQ2JJVbb7GVXZrPLsWtMTbwcKtzkdYqtaFVrV+cDL3tJhKblHWsoScZhdd7ynHhkBLShlsAf+N+nU2KMdf0AllVsxI0RCm4UDYQPVrAdTHtmofHi7dxM2ICgIR19L2SpMajnPFVZAkn/M4uFGD/W7W6laiPf+5b/M7/7vtEfqSXoNtw9X1aRN+xUBa6QCD6Z52YTcbw1Rb9owwpy3rMH4ct0GUPkwnLs7tMJj7t6bZtTS94utsGyvWWfhCCBgPkVQDTRl6SD4vhECynZfW9DT1COVnAYuRAW3hTAxSw61z1sLZbT0u/K/8ZirGiIKnq95PP3LzcNCzLBrvu1KZLp8zs59cKmN0AGMf4J6KU0J0i/kppFLgy3KzMPspKbpWlks4G4q1hL852R6M6nmSEY0mknQnDEAcYyNnsT4X1wg0403Cl9unP0AMMJ5+6HfLgrzCRXk+llRHcY0m+fwaoiLvbhLfdF1YmgB1pcmeoiM7PXkUACodLd69ILCHm3ZDEVlme/tPP0nqiYS4mMn31I6huDuzdAZO7nKZBo2rM6KB+3/QJWvIZx7ghWKFnAUifRldQ3Ik5O9z+HURdJIc0kNl5LGIqnyyHqJPjoGVJr9Bl+To21q3raLOLPDvprdFc5JBLeywzOh5YbZEAhc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
